### ISSUE TITLE
Installing texmaker and mactex with Homebrew (modify the command)

### ISSUE THREAD

**Issue by lenatech** [UB-Mannheim/sci-work-course#159]
Hi,
here's some advices.
I installed the mactex & texmaker with Homebrew
```
brew install mactex texmaker
```
And it told me that the formulas are found in a tap. Hence, it should be installed with Homebrew Cask:

```
brew install caskroom/cask/brew-cask
brew cask install mactex texmaker
```

**Comment by zuphilip** [comment]
Does this means that the [installation with Homebrew as described in our guide](https://github.com/UB-Mannheim/sci-work-course/blob/master/doc/install-macosx.md#homebrew) does not work?

Maybe someone can confirm this. I don't have much experience with Mac, but could also try to ask a colleague on that issue...

**Comment by lenatech** [comment]
Hi @zuphilip 
i don't know if it is because "i already have homebrew" or something
But my steps was like:
$brew update
$brew install mactex
And I got the formula not found like this and also the suggestion:
![screen](https://cloud.githubusercontent.com/assets/5935679/22744086/96a2d6ca-ee1c-11e6-8040-0e573cab24e2.jpg)

And i also had a look at the instruction ![here](https://thetechsolo.wordpress.com/2016/01/28/latex-on-mac-the-easy-way/)

**Comment by zuphilip** [comment]
Okay, thank you for the explanation. I created out of this a PR #162 and added your name, such that you can get the credit for it. Is that okay?
