### ISSUE TITLE
Switch Mac, Linux installation to TeXstudio as well

### ISSUE THREAD

**Issue by zuphilip** [UB-Mannheim/sci-work-course#406]
Any help would be welcome for that @stweil @jmechnich @JKamlah

**Comment by stweil** [comment]
Debian includes a `texstudio` package. I'll try that.

**Comment by zuphilip** [comment]
@stweil For Ubuntu it is available through PPA https://www.texstudio.org/ but I have not enough experience to write up something from just that information.

**Comment by jmechnich** [comment]
The instructions are given on the associated Launchpad page:
```
sudo add-apt-repository ppa:sunderme/texstudio
sudo apt-get update
sudo apt-get install texstudio
```
The AppImage linked from the Download page might also be worth mentioning (should run on most distros).

**Comment by stweil** [comment]
It's also available from Ubuntu universe, so no need for PPA.

**Comment by jmechnich** [comment]
By suggesting the PPA and the Debian package from the download page, we could minimize the chances of having to deal with differences in look & feel, features and bugs in the software as they have the same version as the Windows and Mac releases (2.12.16 at the time of writing). The Debian repository has (as usual) an older version (2.11.2), for Ubuntu it is actually quite recent (2.12.14).
However, as the the number of students using Linux is negligible, it is probably not worth spending too much thought on it. ;)

**Comment by zuphilip** [comment]
Interesting! Can someone of you update the linux installation https://github.com/UB-Mannheim/sci-work-course/blob/master/doc/install-linux.md accordingly and change texmaker there with TeXstudio?

**Comment by jmechnich** [comment]
Done for Linux and MacOS.

**Comment by zuphilip** [comment]
Thank you very much, @jmechnich, :bowing_man: !
