### ISSUE TITLE
Move installation guide (windows) from pdf to markdown here

### ISSUE THREAD

**Issue by zuphilip** [UB-Mannheim/sci-work-course#52]
See http://www.bib.uni-mannheim.de/go-research.html for the current info about installation of LaTeX.

Moreover, we should rethink the place of the FAQs and also add this one: http://tex.stackexchange.com/questions/250472/texniccenter-adobe-reader-dc

**Comment by kba** [comment]
See https://github.com/UB-Mannheim/sci-work-course/tree/windows-latex-install and https://github.com/UB-Mannheim/sci-work-course/blob/windows-latex-install/doc/install-windows.md

**Comment by zuphilip** [comment]
Wow, that looks good! :sleeping:

**Comment by zuphilip** [comment]
I added a sentence and I have one additional comment, see https://github.com/UB-Mannheim/sci-work-course/commit/a57d1effcbe7eccd156706f1c9493fce93724a51#commitcomment-13969138

Otherwise this look good. Feel free to merge into master.
