### ISSUE TITLE
Test your installation for Mac, Linux

### ISSUE THREAD

**Issue by zuphilip** [UB-Mannheim/sci-work-course#80]
The description how to test your installation is only available in Windows: https://github.com/UB-Mannheim/sci-work-course/blob/master/doc/install-windows.md#test-installation . We should also describe these steps for the Mac and Linux environment.

**Comment by kba** [comment]
Should be fixed in vanilla.

**Comment by zuphilip** [comment]
Thank you very much! :bow:
