### ISSUE TITLE
LaTeX Installation Mac: TeXmaker 4.5

### ISSUE THREAD

**Issue by zuphilip** [UB-Mannheim/sci-work-course#98]
In TeXmaker 4.5 the `Configure TeXmaker` changed its position in the menu.

**Comment by kba** [comment]
Where is it now?

**Comment by zuphilip** [comment]
Hm, first or second menu... I have forgotten where exactly it was...

**Comment by stweil** [comment]
Could this be a special git exercise for MAC users in the next course?

**Comment by zuphilip** [comment]
Sure, maybe also tomorrow someone has time to solve this issue, if we mention it.

**Comment by kba** [comment]
Corrected in 635c017
