### ISSUE TITLE
Move FAQs for LaTeX here

### ISSUE THREAD

**Issue by zuphilip** [UB-Mannheim/sci-work-course#99]
The questions from the FAQs about LaTeX should be better moved here as another `.md` file from https://bib.uni-mannheim.de/index.php?id=1129

**Comment by kba** [comment]
+ On Mac: In Texmaker, if "command not found" errors, set up the absolute paths to the tools.

**Comment by kba** [comment]
moved to http://www.bib.uni-mannheim.de/en/cs-course/?
